### ISSUE TITLE
letsencrypt_webfaction init error

### ISSUE THREAD

**Issue by liangjun-jiang** [will-in-wi/letsencrypt-webfaction#126]
Ran:
`
letsencrypt_webfaction init
`
My webfaction terminal shows:
```
/home/abc_user/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.2.3/lib/letsencrypt_webfaction/application.rb:78:in `validate_options!': Invalid domains '[]' (ArgumentError)
Invalid public '[]'
Invalid letsencrypt_account_email ''
Invalid username ''
Invalid password ''
Invalid cert_name ''
	from /home/abc_user/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.2.3/lib/letsencrypt_webfaction/application.rb:17:in `run!'
	from /home/abc_user/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.2.3/exe/letsencrypt_webfaction:5:in `<top (required)>'
	from /home/abc_user/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/abc_user/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

I felt that I should pass args to `letsencrypt_webfaction init`. Did n't see where / how I should pass.

Thanks,

**Comment by will-in-wi** [comment]
The init command is for version 3.0.0, whereas you are running 2.2.3. could you upgrade?
