### ISSUE TITLE
letsencrypt_webfaction run show Error

### ISSUE THREAD

**Issue by wilrona** [will-in-wi/letsencrypt-webfaction#128]
Hello,
I have an error when I execute the "letsencrypt_webfaction run" command. I have this message.

```
/home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:890:in `scan': invalid byte sequence in US-ASCII (ArgumentError)
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:890:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:288:in `apply_rule'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:250:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:1149:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:288:in `apply_rule'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:250:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:780:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:288:in `apply_rule'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:250:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:1149:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:288:in `apply_rule'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:250:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:1206:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:288:in `apply_rule'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:250:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:780:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:288:in `apply_rule'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:250:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:1244:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:288:in `apply_rule'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:250:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:1149:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:288:in `apply_rule'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:250:in `exec'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:665:in `parse'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/citrus-3.0.2/lib/citrus.rb:392:in `parse'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/toml-rb-1.1.1/lib/toml-rb/parser.rb:12:in `initialize'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/toml-rb-1.1.1/lib/toml-rb.rb:46:in `new'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/toml-rb-1.1.1/lib/toml-rb.rb:46:in `parse'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.0.0/lib/letsencrypt_webfaction/options.rb:19:in `from_toml'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.0.0/lib/letsencrypt_webfaction/application/run.rb:24:in `initialize'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.0.0/lib/letsencrypt_webfaction/application.rb:28:in `new'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.0.0/lib/letsencrypt_webfaction/application.rb:28:in `new'
	from /home/marcelj35/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.0.0/exe/letsencrypt_webfaction:7:in `<top (required)>'
	from /home/marcelj35/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/marcelj35/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

I have configured my configuration file: "nano -w ~ / letsencrypt_webfaction.toml" but I still have the same problem.

please help.

**Comment by will-in-wi** [comment]
Could you post an anonymized version of your config? The is an invalid character somewhere in there.

**Comment by dinhtq** [comment]
Hello, I think I got similar issue as the OP.
Here is my anonymized yml:

```
# Configuration file for letsencrypt_webfaction utility
domains: [website.com,wwww.website.com]
public: [~/webapps/app_name]
letsencrypt_account_email: 'email@gmail.com'
username: 'webfaction_username'
password: 'webfaction_password'
cert_name: 'TestCert1111'
endpoint: 'https://acme-staging.api.letsencrypt.org/'
```

When I do:
`letsencrypt_webfaction --config ~/LetsEncryptComboTestConfig.yml
`

I get:
`Unsupported command `--config`. Must be one of init, run`

When I do:
`letsencrypt_webfaction run --config ~/LetsEncryptComboTestConfig.yml`

I get:
`
/home/webfaction_username/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.0.0/lib/letsencrypt_webfaction/application/run.rb:50:in `parse_quiet': invalid option: --config (OptionParser::InvalidOption)
	from /home/webfaction_username/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.0.0/lib/letsencrypt_webfaction/application/run.rb:16:in `initialize'
	from /home/webfaction_username/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.0.0/lib/letsencrypt_webfaction/application.rb:28:in `new'
	from /home/webfaction_username/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.0.0/lib/letsencrypt_webfaction/application.rb:28:in `new'
	from /home/webfaction_username/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.0.0/exe/letsencrypt_webfaction:7:in `<top (required)>'
	from /home/webfaction_username/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/webfaction_username/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
`
Any thoughts?

**Comment by will-in-wi** [comment]
@dinhtq this is a different issue from that of the OP. You are trying to use a v2 config and params with the v3 client. You can see the upgrading document about how to rework the configuration.
