### ISSUE TITLE
Error for 1 certificate in cron, not manually

### ISSUE THREAD

**Issue by jpdupont** [will-in-wi/letsencrypt-webfaction#154]
My cron file renews 5 certificates at the same time. I received 4 mails successfully, and one with these error messages. But when I renew this certificate manually by running the config.yml file, it happens without error.
====== mail with errors =======
```
/home/myapp/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/acme-client-0.6.2/lib/acme/client/faraday_middleware.rb:43:in `raise_on_error!': Error creating new registration (Acme::Client::Error::ServerInternal)
	from /home/myapp/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/acme-client-0.6.2/lib/acme/client/faraday_middleware.rb:33:in `on_complete'
	from /home/myapp/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/acme-client-0.6.2/lib/acme/client/faraday_middleware.rb:18:in `block in call'
	from /home/myapp/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.13.1/lib/faraday/response.rb:61:in `on_complete'
	from /home/myapp/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/acme-client-0.6.2/lib/acme/client/faraday_middleware.rb:18:in `call'
	from /home/myapp/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
	from /home/myapp/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
	from /home/myapp/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.13.1/lib/faraday/connection.rb:174:in `post'
	from /home/myapp/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/acme-client-0.6.2/lib/acme/client.rb:56:in `register'
	from /home/myapp/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/letsencrypt_webfaction-2.2.3/lib/letsencrypt_webfaction/application.rb:70:in `register_key!'
	from /home/myapp/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/letsencrypt_webfaction-2.2.3/lib/letsencrypt_webfaction/application.rb:26:in `run!'
	from /home/myapp/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/letsencrypt_webfaction-2.2.3/exe/letsencrypt_webfaction:5:in `<top (required)>'
	from /home/myapp/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/myapp/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

**Comment by will-in-wi** [comment]
Based on the error class: `Acme::Client::Error::ServerInternal`, I'd think that this was a transient error due to upstream breaking. Are you seeing this consistently or was this a one-off?

If the latter, I'd ignore it unless it happens again.

**Comment by jpdupont** [comment]
Thanks William, 
very happy with your work on Lest'sencrypt !!!
