### ISSUE TITLE
Acme::Client::Error::AccountDoesNotExist

### ISSUE THREAD

**Issue by bwareham** [will-in-wi/letsencrypt-webfaction#168]
I had been using Webfaction's tool for generating Let's Encrypt certificates, but it appears to be disabled for issuing new ones and there's no sign of whether it will be reactivated. So, I installed this tool and seem to have everything configured, but get this error when I run it.
```
/home/bwareham/.letsencrypt_webfaction/gems/gems/acme-client-2.0.6/lib/acme/client/faraday_middleware.rb:54:in `raise_on_error!': No account exists with the provided key (Acme::Client::Error::AccountDoesNotExist)
	from /home/bwareham/.letsencrypt_webfaction/gems/gems/acme-client-2.0.6/lib/acme/client/faraday_middleware.rb:38:in `on_complete'
	from /home/bwareham/.letsencrypt_webfaction/gems/gems/acme-client-2.0.6/lib/acme/client/faraday_middleware.rb:23:in `block in call'
	from /home/bwareham/.letsencrypt_webfaction/gems/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
	from /home/bwareham/.letsencrypt_webfaction/gems/gems/acme-client-2.0.6/lib/acme/client/faraday_middleware.rb:23:in `call'
	from /home/bwareham/.letsencrypt_webfaction/gems/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
	from /home/bwareham/.letsencrypt_webfaction/gems/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
	from /home/bwareham/.letsencrypt_webfaction/gems/gems/faraday-1.0.1/lib/faraday/connection.rb:279:in `post'
	from /home/bwareham/.letsencrypt_webfaction/gems/gems/acme-client-2.0.6/lib/acme/client.rb:260:in `post'
	from /home/bwareham/.letsencrypt_webfaction/gems/gems/acme-client-2.0.6/lib/acme/client.rb:89:in `account'
	from /home/bwareham/.letsencrypt_webfaction/gems/gems/acme-client-2.0.6/lib/acme/client.rb:99:in `kid'
	from /home/bwareham/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-4.0.1/lib/letsencrypt_webfaction/application/run.rb:166:in `register_key'
	from /home/bwareham/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-4.0.1/lib/letsencrypt_webfaction/application/run.rb:35:in `run!'
	from /home/bwareham/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-4.0.1/exe/letsencrypt_webfaction:8:in `<top (required)>'
	from /home/bwareham/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/bwareham/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

**Comment by bwareham** [comment]
I tried changing the email address in the .toml file after finding that worked for others who had similar problems with acme clients, but it didn't resolve my problem. HOWEVER, Webfaction's Let Encrypt button mysteriously showed up today as an option for my newly created site, so I was able to generate a certificate. If you have no interest in digging into this issue please feel free to close it.
