### ISSUE TITLE
Fails to run with acme-client >= 0.3.2

### ISSUE THREAD

**Issue by pedrokiefer** [will-in-wi/letsencrypt-webfaction#26]
Stack trace acme-client 0.3.2:
```
/home/pedrokiefer/.letsencrypt_webfaction/gems/gems/acme-client-0.3.2/lib/acme/client.rb:1:in `<top (required)>': uninitialized constant Acme (NameError)
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/pedrokiefer/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/lib/letsencrypt_webfaction/application.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/pedrokiefer/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/exe/letsencrypt_webfaction:3:in `<top (required)>'
	from /home/pedrokiefer/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/pedrokiefer/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

Stack trace acme-client 0.3.3:
```
/home/pedrokiefer/.letsencrypt_webfaction/gems/gems/acme-client-0.3.3/lib/acme/client.rb:1:in `<top (required)>': uninitialized constant Acme (NameError)
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/pedrokiefer/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/lib/letsencrypt_webfaction/application.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/pedrokiefer/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/exe/letsencrypt_webfaction:3:in `<top (required)>'
	from /home/pedrokiefer/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/pedrokiefer/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

**Comment by will-in-wi** [comment]
Thanks! I'm looking into it.

**Comment by will-in-wi** [comment]
I just pushed version 1.1.1 to RubyGems. Could you try that?

Thanks!

**Comment by pedrokiefer** [comment]
Great, thanks! :)
