### ISSUE TITLE
Error during common usage

### ISSUE THREAD

**Issue by spescina** [will-in-wi/letsencrypt-webfaction#27]
Hi

I am trying to use your tool but I have an error.
```
/home/myuser/.letsencrypt_webfaction/gems/gems/acme-client-0.3.3/lib/acme/client/faraday_middleware.rb:37:in `raise_on_error!': algorithm 'none' in JWS header not acceptable (Acme::Client::Error::Malformed)
        from /home/myuser/.letsencrypt_webfaction/gems/gems/acme-client-0.3.3/lib/acme/client/faraday_middleware.rb:27:in `on_complete'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/acme-client-0.3.3/lib/acme/client/faraday_middleware.rb:12:in `block in call'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/acme-client-0.3.3/lib/acme/client/faraday_middleware.rb:12:in `call'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/acme-client-0.3.3/lib/acme/client.rb:23:in `register'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.1/lib/letsencrypt_webfaction/application.rb:70:in `register_key!'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.1/lib/letsencrypt_webfaction/application.rb:21:in `run!'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.1/exe/letsencrypt_webfaction:5:in `<top (required)>'
        from /home/myuser/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
        from /home/myuser/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

config file
```
key_size: 4096
endpoint: 'https://acme-v01.api.letsencrypt.org/'
account_email: 'me@example.com'
support_email: 'me@example.com'
domains:
  - 'sub.domain.com'
public: '/home/myuser/webapps/satis_src/public/'
```

command
`letsencrypt_webfaction --config ~/le_config.yml`

box 461
no error while installing.
Tnx

**Comment by will-in-wi** [comment]
It looks like this is fallout from https://github.com/unixcharles/acme-client/issues/74

I just released version 1.1.2. Could you give that a shot?

Thanks!

**Comment by spescina** [comment]
Fixed. Thanks a lot.
Bye

**Comment by will-in-wi** [comment]
Glad to hear it worked for you!
