### ISSUE TITLE
Gmail configuration issue

### ISSUE THREAD

**Issue by SNaushadS** [will-in-wi/letsencrypt-webfaction#35]
Earlier i was getting errors when using GMail.

As instructed i created the le_config.yml file and added the details.
:user_name: '[_my gmail address_]'
    :password: '[_used the app specific password without spaces_]'

- I have retained the Square brackets, not sure if that is correct.
- The password is App Specific Password as i am using 2FA.

The error that i am getting now is as follows:
```
/usr/local/lib/ruby22/ruby/2.2.0/net/smtp.rb:976:in `check_auth_response': 535-5.7.8 Username and Password not accepted. Learn more at (Net::SMTPAuthenticationError)
        from /usr/local/lib/ruby22/ruby/2.2.0/net/smtp.rb:740:in `auth_plain'
        from /usr/local/lib/ruby22/ruby/2.2.0/net/smtp.rb:732:in `authenticate'
        from /usr/local/lib/ruby22/ruby/2.2.0/net/smtp.rb:567:in `do_start'
        from /usr/local/lib/ruby22/ruby/2.2.0/net/smtp.rb:520:in `start'
        from /home/WF_USERNAME/.letsencrypt_webfaction/gems/gems/mail-2.6.4/lib/mail/network/delivery_methods/smtp.rb:113:in `deliver!'
        from /home/WF_USERNAME/.letsencrypt_webfaction/gems/gems/mail-2.6.4/lib/mail/message.rb:253:in `deliver!'
        from /home/WF_USERNAME/.letsencrypt_webfaction/gems/gems/pony-1.11/lib/pony.rb:176:in `deliver'
        from /home/WF_USERNAME/.letsencrypt_webfaction/gems/gems/pony-1.11/lib/pony.rb:166:in `mail'
        from /home/WF_USERNAME/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/lib/letsencrypt_webfaction/emailer.rb:27:in `send_to_support!'
        from /home/WF_USERNAME/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/lib/letsencrypt_webfaction/emailer.rb:21:in `send!'
        from /home/WF_USERNAME/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/lib/letsencrypt_webfaction/application.rb:30:in `run!'
        from /home/WF_USERNAME/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.0/exe/letsencrypt_webfaction:5:in `<top (required)>'
        from /home/WF_USERNAME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
        from /home/WF_USERNAME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

Should i try using Webfaction hosted email or Non-Gmail ID ?

Please assist.

**Comment by will-in-wi** [comment]
In this case, I would confirm that the App Specific Password is set up correctly. The error `Username and Password not accepted` indicates that Gmail is receiving your credentials, but they aren't correct. Alternatively, make sure you have passed `-c le_config.yml` to `letsencrypt_webfaction`.

Trying Webfaction hosted email or Non-Gmail ID might work, you just have to make sure it is associated with your WebFaction account.

**Comment by will-in-wi** [comment]
Did this work for you?

**Comment by SNaushadS** [comment]
Had Tried non-gmail id and it works. Thanks

**Comment by will-in-wi** [comment]
I'm glad to hear it!
