### ISSUE TITLE
Add pry as a dependancy of this gem 

### ISSUE THREAD

**Issue by paulrobertlloyd** [will-in-wi/letsencrypt-webfaction#42]
Upgrading to the latest version (1.1.7), I was getting the following error after running `letsencrypt_webfaction`

```
[prlloyd@web520 ~]$ letsencrypt_webfaction --help
/usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- pry (LoadError)
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/prlloyd/.letsencrypt/gems/gems/letsencrypt_webfaction-1.1.7/lib/letsencrypt_webfaction/domain_validator.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/prlloyd/.letsencrypt/gems/gems/letsencrypt_webfaction-1.1.7/lib/letsencrypt_webfaction/application.rb:5:in `<top (required)>'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby22/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/prlloyd/.letsencrypt/gems/gems/letsencrypt_webfaction-1.1.7/exe/letsencrypt_webfaction:3:in `<top (required)>'
	from /home/prlloyd/.letsencrypt/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/prlloyd/.letsencrypt/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

I was able to fix this by manually installing pry (`gem2.2 install pry`). Shouldn’t pry be added as a dependancy of the letsencrypt-webfaction gem?

**Comment by will-in-wi** [comment]
Pry is a debugging tool which I accidentally left in… I've removed it and pushed a hotfix release 1.1.8 without the dependency.

Please let me know if 1.1.8 is still an issue.

Thanks!

**Comment by paulrobertlloyd** [comment]
Ah, that was quick! Yup, all works as planned, thanks. And thanks for putting this tool together—saves me so much hassle… well, at least once every three months :-)

**Comment by will-in-wi** [comment]
My pleasure! Glad it is useful for you.
