### ISSUE TITLE
Renew command fails with "Connection reseted by Peer"

### ISSUE THREAD

**Issue by hellvix** [will-in-wi/letsencrypt-webfaction#52]
For testing purposes I tried to run the renew command and I got the following error:

```
$ PATH=$PATH:$GEM_HOME/bin:/usr/local/bin GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib ruby2.2 $HOME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction --account_email webmaster@mysite.dk --domains mysite.dk,www.mysite.dk,dev.mysite.dk --public ~/webapps/mysite_main_redirect/ 

/usr/local/lib/ruby22/ruby/2.2.0/net/http.rb:923:in `connect': Connection reset by peer - SSL_connect (Faraday::ConnectionFailed)
        from /usr/local/lib/ruby22/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from /usr/local/lib/ruby22/ruby/2.2.0/timeout.rb:73:in `timeout'
        from /usr/local/lib/ruby22/ruby/2.2.0/net/http.rb:923:in `connect'
        from /usr/local/lib/ruby22/ruby/2.2.0/net/http.rb:863:in `do_start'
        from /usr/local/lib/ruby22/ruby/2.2.0/net/http.rb:852:in `start'
        from /usr/local/lib/ruby22/ruby/2.2.0/net/http.rb:1375:in `request'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `head'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday.rb:99:in `method_missing'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/acme-client-0.4.1/lib/acme/client/faraday_middleware.rb:108:in `get_nonce'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/acme-client-0.4.1/lib/acme/client/faraday_middleware.rb:101:in `pop_nonce'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/acme-client-0.4.1/lib/acme/client/faraday_middleware.rb:17:in `call'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/acme-client-0.4.1/lib/acme/client.rb:45:in `register'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.8/lib/letsencrypt_webfaction/application.rb:70:in `register_key!'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.8/lib/letsencrypt_webfaction/application.rb:21:in `run!'
        from /home/myuser/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-1.1.8/exe/letsencrypt_webfaction:5:in `<top (required)>'
        from /home/myuser/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
        from /home/myuser/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'

```

Is it supposed to happen because the certificate can't get renewed?

**Comment by will-in-wi** [comment]
I haven't seen this one before. You might try these instructions: https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Troubleshooting#ssl_connect-returned1-errno0-stateerror-certificate-verify-failed-faradaysslerror

**Comment by hellvix** [comment]
OK. I'll try.

**Comment by hellvix** [comment]
Well, for some weird reason it simply worked. I guess we can call it closed.
