### ISSUE TITLE
Invalid username and password

### ISSUE THREAD

**Issue by SNaushadS** [will-in-wi/letsencrypt-webfaction#63]
I have created the le_config.yml file by referring to the sample file

contents are as below:

`key_size: 4096
# We need an ACME server to talk to, see github.com/letsencrypt/boulder
endpoint: 'https://acme-v01.api.letsencrypt.org/'
letsencrypt_account_email: 'sns_planes@yahoo.co.in'
api_url: 'https://api.webfaction.com/'
username: 'ACCOUNTNAME'
password: 'CONTROL_PANEL_PASSWORD'`

Crontab:

```
MAILFROM=ACCOUNT_NAME@web409.webfaction.com
MAILTO=MY_EMAILID

31 14 * * * PATH=$PATH:$GEM_HOME/bin:/usr/local/bin GEM_HOME=/home/ACCOUNT_NAME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib ruby2.2 /home/ACCOUNT_NAME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction --letsencrypt_account_email MY_EMAILID --domains domain.in,www.domain.in --public ~/webapps/chokho/ >> /home/ACCOUNT_NAME/logs/user/cron.log 2>&1
```

Error that i get is from log: 
```
/home/ACCOUNT_NAME/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/application.rb:69:in `validate_options!': Invalid username '' (ArgumentError)
Invalid password ''
        from /home/ACCOUNT_NAME/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/application.rb:17:in `run!'
        from /home/ACCOUNT_NAME/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/exe/letsencrypt_webfaction:5:in `<top (required)>'
        from /home/ACCOUNT_NAME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
        from /home/ACCOUNT_NAME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

Would appreciate some help.

Some additional query that i have pertaining to config file.

Are there any mandatory options to be kept there ? say, i dont want to mess with key_size Or endpoint or api_url. Can i remove them completely and assume that it would be defaulted by script ?

**Comment by will-in-wi** [comment]
I think you are missing the config argument for the command. E.g. you probably need to add `--config ~/le_config.yml` to `letsencrypt_webfaction`.

Does this fix it?

**Comment by SNaushadS** [comment]
Hey @will-in-wi , thanks for the help. that worked and i was able to renew the cert. Thanks again for the help. Seasons greetings.
