### ISSUE TITLE
LoginError (XMLRPC::FaultException)

### ISSUE THREAD

**Issue by gour** [will-in-wi/letsencrypt-webfaction#75]
Hello, I'm having same/similar issues as #55...when I execute `letsencrypt_webfaction` and pass all the parameters via cli, it works, but when I do the same via config file:

```
cat org.yml 
# See config.defaults.yml for all available settings.

key_size: 4096
letsencrypt_account_email: 'myemail@domain.tld'
domains:
  - 'mydomain.domain.ltd'
# The webroot of the application.
public: '/home/myuserid/webapps/appfolder/'
username: "myusername"
password: "mypasswd"
```

I get the following:

```
etsencrypt_webfaction --config ./org.yml 
/usr/local/lib/ruby22/ruby/2.2.0/xmlrpc/client.rb:271:in `call': LoginError (XMLRPC::FaultException)
	from /home/atmarama/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/certificate_installer.rb:33:in `session_id'
	from /home/atmarama/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/certificate_installer.rb:14:in `install!'
	from /home/atmarama/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/lib/letsencrypt_webfaction/application.rb:26:in `run!'
	from /home/atmarama/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-2.0.0/exe/letsencrypt_webfaction:5:in `<top (required)>'
	from /home/atmarama/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `load'
	from /home/atmarama/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in `<main>'
```

Any hint?

**Comment by will-in-wi** [comment]
Offhand, I'd double-check that your username/password is correct. It is also possible that the password has characters which the API doesn't accept.

**Comment by gour** [comment]
> Offhand, I'd double-check that your username/password is correct.

Ahh...feeling very stupid now. :-(
All the time I was checking whether my passwd is okay, but forgot to check username - I put my regular uid used on my private machines. :-(

**Comment by will-in-wi** [comment]
No problem. 😄 I've done this myself many a time.
